=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "address".pluralize.to_sym, id: false do |t|
      t.integer :address_id
      t.string :address_line1
      t.string :address_line2
      t.string :city
      t.string :state_province
      t.string :country_region
      t.string :postal_code
      t.string :rowguid
      t.datetime :modified_date
      t.string :customer_address
      t.string :sales_order_header_bill_to_address
      t.string :sales_order_header_ship_to_address

      t.timestamps
    end

    create_table "customer".pluralize.to_sym, id: false do |t|
      t.integer :customer_id
      t.boolean :name_style
      t.string :title
      t.string :first_name
      t.string :middle_name
      t.string :last_name
      t.string :suffix
      t.string :company_name
      t.string :sales_person
      t.string :email_address
      t.string :phone
      t.string :password_hash
      t.string :password_salt
      t.string :rowguid
      t.datetime :modified_date
      t.string :customer_address
      t.string :sales_order_header

      t.timestamps
    end

    create_table "customer_address".pluralize.to_sym, id: false do |t|
      t.integer :customer_id
      t.integer :address_id
      t.string :address_type
      t.string :rowguid
      t.datetime :modified_date
      t.string :address
      t.string :customer

      t.timestamps
    end

    create_table "error_log".pluralize.to_sym, id: false do |t|
      t.integer :error_log_id
      t.datetime :error_time
      t.integer :error_number
      t.integer :error_severity
      t.integer :error_state
      t.string :error_procedure
      t.integer :error_line
      t.string :error_message

      t.timestamps
    end

    create_table "product".pluralize.to_sym, id: false do |t|
      t.integer :product_id
      t.string :name
      t.string :product_number
      t.string :color
      t.decimal :standard_cost
      t.decimal :list_price
      t.string :size
      t.decimal :weight
      t.integer :product_category_id
      t.integer :product_model_id
      t.datetime :sell_start_date
      t.datetime :sell_end_date
      t.datetime :discontinued_date
      t.string :thumb_nail_photo
      t.string :thumbnail_photo_file_name
      t.string :rowguid
      t.datetime :modified_date
      t.string :product_category
      t.string :product_model
      t.string :sales_order_detail

      t.timestamps
    end

    create_table "product_category".pluralize.to_sym, id: false do |t|
      t.integer :product_category_id
      t.integer :parent_product_category_id
      t.string :name
      t.string :rowguid
      t.datetime :modified_date
      t.string :parent_product_category
      t.string :inverse_parent_product_category
      t.string :product

      t.timestamps
    end

    create_table "product_description".pluralize.to_sym, id: false do |t|
      t.integer :product_description_id
      t.string :description
      t.string :rowguid
      t.datetime :modified_date
      t.string :product_model_product_description

      t.timestamps
    end

    create_table "product_model".pluralize.to_sym, id: false do |t|
      t.integer :product_model_id
      t.string :name
      t.string :catalog_description
      t.string :rowguid
      t.datetime :modified_date
      t.string :product
      t.string :product_model_product_description

      t.timestamps
    end

    create_table "product_model_product_description".pluralize.to_sym, id: false do |t|
      t.integer :product_model_id
      t.integer :product_description_id
      t.string :culture
      t.string :rowguid
      t.datetime :modified_date
      t.string :product_description
      t.string :product_model

      t.timestamps
    end

    create_table "sales_order_detail".pluralize.to_sym, id: false do |t|
      t.integer :sales_order_id
      t.integer :sales_order_detail_id
      t.integer :order_qty
      t.integer :product_id
      t.decimal :unit_price
      t.decimal :unit_price_discount
      t.decimal :line_total
      t.string :rowguid
      t.datetime :modified_date
      t.string :product
      t.string :sales_order

      t.timestamps
    end

    create_table "sales_order_header".pluralize.to_sym, id: false do |t|
      t.integer :sales_order_id
      t.integer :revision_number
      t.datetime :order_date
      t.datetime :due_date
      t.datetime :ship_date
      t.integer :status
      t.boolean :online_order_flag
      t.string :sales_order_number
      t.string :purchase_order_number
      t.string :account_number
      t.integer :customer_id
      t.integer :ship_to_address_id
      t.integer :bill_to_address_id
      t.string :ship_method
      t.string :credit_card_approval_code
      t.decimal :sub_total
      t.decimal :tax_amt
      t.decimal :freight
      t.decimal :total_due
      t.string :comment
      t.string :rowguid
      t.datetime :modified_date
      t.string :bill_to_address
      t.string :customer
      t.string :ship_to_address
      t.string :sales_order_detail

      t.timestamps
    end

  end
end
