=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Address < ApplicationRecord

  serialize :customer_address, Array
  serialize :sales_order_header_bill_to_address, Array
  serialize :sales_order_header_ship_to_address, Array
end
