=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Customer < ApplicationRecord

  serialize :customer_address, Array
  serialize :sales_order_header, Array
end
