=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class ProductCategory < ApplicationRecord

  serialize :inverse_parent_product_category, Array
  serialize :product, Array
end
