=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class ProductModel < ApplicationRecord

  serialize :product, Array
  serialize :product_model_product_description, Array
end
