=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AddressesController < ApplicationController

  def delete_address
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_address
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_address_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_address
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_address
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
