=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CustomersController < ApplicationController

  def delete_customer
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_customer
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_customer_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_customer
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_customer
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
