=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ErrorLogsController < ApplicationController

  def delete_error_log
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_error_log
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_error_log_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_error_log
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_error_log
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
