=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ProductsController < ApplicationController

  def delete_product
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_product
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_product_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_product
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_product
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
