=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ProductCategoriesController < ApplicationController

  def delete_product_category
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_product_category
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_product_category_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_product_category
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_product_category
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
