=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SalesOrderHeadersController < ApplicationController

  def delete_sales_order_header
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_sales_order_header
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_sales_order_header_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post_sales_order_header
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put_sales_order_header
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
