=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ValuesController < ApplicationController

  def delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
