=begin
AdventureWorksAPI

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
Rails.application.routes.draw do

  def add_swagger_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_swagger_route 'DELETE', '/api/Addresses/{id}', controller_name: 'addresses', action_name: 'delete_address'
  add_swagger_route 'GET', '/api/Addresses', controller_name: 'addresses', action_name: 'get_address'
  add_swagger_route 'GET', '/api/Addresses/{id}', controller_name: 'addresses', action_name: 'get_address_1'
  add_swagger_route 'POST', '/api/Addresses', controller_name: 'addresses', action_name: 'post_address'
  add_swagger_route 'PUT', '/api/Addresses/{id}', controller_name: 'addresses', action_name: 'put_address'
  add_swagger_route 'DELETE', '/api/CustomerAddresses/{id}', controller_name: 'customerAddresses', action_name: 'delete_customer_address'
  add_swagger_route 'GET', '/api/CustomerAddresses', controller_name: 'customerAddresses', action_name: 'get_customer_address'
  add_swagger_route 'GET', '/api/CustomerAddresses/{id}', controller_name: 'customerAddresses', action_name: 'get_customer_address_1'
  add_swagger_route 'POST', '/api/CustomerAddresses', controller_name: 'customerAddresses', action_name: 'post_customer_address'
  add_swagger_route 'PUT', '/api/CustomerAddresses/{id}', controller_name: 'customerAddresses', action_name: 'put_customer_address'
  add_swagger_route 'DELETE', '/api/Customers/{id}', controller_name: 'customers', action_name: 'delete_customer'
  add_swagger_route 'GET', '/api/Customers', controller_name: 'customers', action_name: 'get_customer'
  add_swagger_route 'GET', '/api/Customers/{id}', controller_name: 'customers', action_name: 'get_customer_1'
  add_swagger_route 'POST', '/api/Customers', controller_name: 'customers', action_name: 'post_customer'
  add_swagger_route 'PUT', '/api/Customers/{id}', controller_name: 'customers', action_name: 'put_customer'
  add_swagger_route 'DELETE', '/api/ErrorLogs/{id}', controller_name: 'errorLogs', action_name: 'delete_error_log'
  add_swagger_route 'GET', '/api/ErrorLogs', controller_name: 'errorLogs', action_name: 'get_error_log'
  add_swagger_route 'GET', '/api/ErrorLogs/{id}', controller_name: 'errorLogs', action_name: 'get_error_log_1'
  add_swagger_route 'POST', '/api/ErrorLogs', controller_name: 'errorLogs', action_name: 'post_error_log'
  add_swagger_route 'PUT', '/api/ErrorLogs/{id}', controller_name: 'errorLogs', action_name: 'put_error_log'
  add_swagger_route 'DELETE', '/api/ProductCategories/{id}', controller_name: 'productCategories', action_name: 'delete_product_category'
  add_swagger_route 'GET', '/api/ProductCategories', controller_name: 'productCategories', action_name: 'get_product_category'
  add_swagger_route 'GET', '/api/ProductCategories/{id}', controller_name: 'productCategories', action_name: 'get_product_category_1'
  add_swagger_route 'POST', '/api/ProductCategories', controller_name: 'productCategories', action_name: 'post_product_category'
  add_swagger_route 'PUT', '/api/ProductCategories/{id}', controller_name: 'productCategories', action_name: 'put_product_category'
  add_swagger_route 'DELETE', '/api/ProductDescriptions/{id}', controller_name: 'productDescriptions', action_name: 'delete_product_description'
  add_swagger_route 'GET', '/api/ProductDescriptions', controller_name: 'productDescriptions', action_name: 'get_product_description'
  add_swagger_route 'GET', '/api/ProductDescriptions/{id}', controller_name: 'productDescriptions', action_name: 'get_product_description_1'
  add_swagger_route 'POST', '/api/ProductDescriptions', controller_name: 'productDescriptions', action_name: 'post_product_description'
  add_swagger_route 'PUT', '/api/ProductDescriptions/{id}', controller_name: 'productDescriptions', action_name: 'put_product_description'
  add_swagger_route 'DELETE', '/api/ProductModelProductDescriptions/{id}', controller_name: 'productModelProductDescriptions', action_name: 'delete_product_model_product_description'
  add_swagger_route 'GET', '/api/ProductModelProductDescriptions', controller_name: 'productModelProductDescriptions', action_name: 'get_product_model_product_description'
  add_swagger_route 'GET', '/api/ProductModelProductDescriptions/{id}', controller_name: 'productModelProductDescriptions', action_name: 'get_product_model_product_description_1'
  add_swagger_route 'POST', '/api/ProductModelProductDescriptions', controller_name: 'productModelProductDescriptions', action_name: 'post_product_model_product_description'
  add_swagger_route 'PUT', '/api/ProductModelProductDescriptions/{id}', controller_name: 'productModelProductDescriptions', action_name: 'put_product_model_product_description'
  add_swagger_route 'DELETE', '/api/ProductModels/{id}', controller_name: 'productModels', action_name: 'delete_product_model'
  add_swagger_route 'GET', '/api/ProductModels', controller_name: 'productModels', action_name: 'get_product_model'
  add_swagger_route 'GET', '/api/ProductModels/{id}', controller_name: 'productModels', action_name: 'get_product_model_1'
  add_swagger_route 'POST', '/api/ProductModels', controller_name: 'productModels', action_name: 'post_product_model'
  add_swagger_route 'PUT', '/api/ProductModels/{id}', controller_name: 'productModels', action_name: 'put_product_model'
  add_swagger_route 'DELETE', '/api/Products/{id}', controller_name: 'products', action_name: 'delete_product'
  add_swagger_route 'GET', '/api/Products', controller_name: 'products', action_name: 'get_product'
  add_swagger_route 'GET', '/api/Products/{id}', controller_name: 'products', action_name: 'get_product_1'
  add_swagger_route 'POST', '/api/Products', controller_name: 'products', action_name: 'post_product'
  add_swagger_route 'PUT', '/api/Products/{id}', controller_name: 'products', action_name: 'put_product'
  add_swagger_route 'DELETE', '/api/SalesOrderDetails/{id}', controller_name: 'salesOrderDetails', action_name: 'delete_sales_order_detail'
  add_swagger_route 'GET', '/api/SalesOrderDetails', controller_name: 'salesOrderDetails', action_name: 'get_sales_order_detail'
  add_swagger_route 'GET', '/api/SalesOrderDetails/{id}', controller_name: 'salesOrderDetails', action_name: 'get_sales_order_detail_1'
  add_swagger_route 'POST', '/api/SalesOrderDetails', controller_name: 'salesOrderDetails', action_name: 'post_sales_order_detail'
  add_swagger_route 'PUT', '/api/SalesOrderDetails/{id}', controller_name: 'salesOrderDetails', action_name: 'put_sales_order_detail'
  add_swagger_route 'DELETE', '/api/SalesOrderHeaders/{id}', controller_name: 'salesOrderHeaders', action_name: 'delete_sales_order_header'
  add_swagger_route 'GET', '/api/SalesOrderHeaders', controller_name: 'salesOrderHeaders', action_name: 'get_sales_order_header'
  add_swagger_route 'GET', '/api/SalesOrderHeaders/{id}', controller_name: 'salesOrderHeaders', action_name: 'get_sales_order_header_1'
  add_swagger_route 'POST', '/api/SalesOrderHeaders', controller_name: 'salesOrderHeaders', action_name: 'post_sales_order_header'
  add_swagger_route 'PUT', '/api/SalesOrderHeaders/{id}', controller_name: 'salesOrderHeaders', action_name: 'put_sales_order_header'
  add_swagger_route 'DELETE', '/api/Values/{id}', controller_name: 'values', action_name: 'delete'
  add_swagger_route 'GET', '/api/Values', controller_name: 'values', action_name: 'get'
  add_swagger_route 'GET', '/api/Values/{id}', controller_name: 'values', action_name: 'get_1'
  add_swagger_route 'POST', '/api/Values', controller_name: 'values', action_name: 'post'
  add_swagger_route 'PUT', '/api/Values/{id}', controller_name: 'values', action_name: 'put'
end
